### PR TITLE
#30 Add Native Json serialisation

### PR DESCRIPTION
**Pull request by baoduy**
Add Native Json serialization by using System.Text.Json library. 

Signed-off-by: Steven Hoang <drunkcoding@outlook.com>

### CODE REVIEW

**Comment by baoduy** [comment]
Hi @zarusz How could I sign-off the PR when forgot to add the sing-off message when submitting the commits?

**Comment by zarusz** [comment]
Hey @baoduy ,

I did some research about how other libraries call their plugin packages when they use the native JSON serializer:

https://www.nuget.org/packages/Amazon.Lambda.Serialization.SystemTextJson
https://www.nuget.org/packages/NodaTime.Serialization.SystemTextJson
https://www.nuget.org/packages/Google.Events.SystemTextJson
https://www.nuget.org/packages/RestSharp.Serializers.SystemTextJson

The `Library.Json` is still reserved for `Newtonsoft.Json` as for SMB.

Therefore, can you change the csproj, readme and other references to `SlimMessageBus.Host.Serialization.SystemTextJson` ?

Also, please add that new plugin to the list inside `build/tasks.ps1` script.

Once that happens, I am happy to approve the PR!

**Comment by baoduy** [comment]
Hi @zarusz as suggested the rename was done :)

**Comment by zarusz** [comment]
@baoduy  this has been merged now, I will test some more and release it within a day or so. 
Thanks for your contribution!

**Pull request merged**
